<a href="https://colab.research.google.com/github/SushanthKumble/DATASCIENCE/blob/main/text_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
import pandas as pd
import re
import string

In [5]:
# to read train set and extract features
data= pd.read_csv("/content/drive/MyDrive/DATA SCIENCE LAB/sample_text - Sheet1.csv")## add the path to train file

In [6]:
data.head()

,tweet_id,text,task1
0,1123757263427186690,"hate wen females hit ah nigga with tht bro ðŸ˜‚ðŸ˜‚,...",HOF
1,1123733301397733380,RT @airjunebug: When you're from the Bay but y...,HOF
2,1123734094108659712,RT @DonaldJTrumpJr: Dear Democrats: The Americ...,NOT
3,1126951188170199049,RT @SheLoveTimothy: He ainâ€™t on drugs he just ...,HOF
4,1126863510447710208,RT @TavianJordan: Summer â€˜19 Iâ€™m coming for yo...,NOT

In [7]:
# def clean_text(text):
#     text = re.sub('@[a-zA-Z0-9]*', '', text)
#     # text = "".join([word.lower() for word in text if word not in string.punctuation])
#     # text = "".join([word for word in text if not word.isdigit()])
#    return text



def clean_text(text):
     text = re.sub('@[a-zA-Z0-9]*', '', text)

     return text
data["clean"] = data["text"].apply(lambda x: clean_text(x))

In [8]:
data.head()

,tweet_id,text,task1,clean
0,1123757263427186690,"hate wen females hit ah nigga with tht bro ðŸ˜‚ðŸ˜‚,...",HOF,"hate wen females hit ah nigga with tht bro ðŸ˜‚ðŸ˜‚,..."
1,1123733301397733380,RT @airjunebug: When you're from the Bay but y...,HOF,RT : When you're from the Bay but you're reall...
2,1123734094108659712,RT @DonaldJTrumpJr: Dear Democrats: The Americ...,NOT,RT : Dear Democrats: The American people arenâ€™...
3,1126951188170199049,RT @SheLoveTimothy: He ainâ€™t on drugs he just ...,HOF,RT : He ainâ€™t on drugs he just bored. I be doi...
4,1126863510447710208,RT @TavianJordan: Summer â€˜19 Iâ€™m coming for yo...,NOT,RT : Summer â€˜19 Iâ€™m coming for you ! No boring...